test_liste/test_liste/urls.py
from django.contrib import admin
from django.urls import path
from liste import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.test, name='test'),
    path('prestation/add/', views.prestation_create, name='prestation-create'),
    path('devis/add/', views.devis_create, name='devis-create'),
    path('get-artiste/<int:artiste_id>/', views.get_artiste, name='get-artiste'),
    path('some-view/', views.some_view, name='some-view'),
    path('calcul/', views.calcul, name='calcul'),
]

test_liste/liste/models.py
from django.db import models

class Prestation(models.Model):
    artiste = models.fields.CharField(max_length=50)
    titre_spectacle = models.fields.CharField(max_length=50)
    nb_artiste = models.fields.IntegerField(null=True, blank=True)
    nb_technicien = models.fields.IntegerField(null=True, blank=True)
    duree_spectacle = models.fields.TimeField(null=True, blank=True)
    cachet_ttc = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    mail = models.fields.EmailField(max_length=50, blank=True)
    designation_spectacle = models.fields.TextField(blank=True)


    def __str__(self):
        return f'{self.artiste}'


class Devis(models.Model):
    numero = models.fields.CharField(max_length=30, blank=True)
    date_crea = models.fields.DateField()
    objet = models.fields.CharField(max_length=50, blank=True)

    artiste = models.ForeignKey(Prestation, null=True, blank=True, on_delete=models.CASCADE)
    titre_spectacle = models.fields.CharField(max_length=50, blank=True)
    nb_artiste = models.fields.IntegerField(null=True, blank=True)
    nb_technicien = models.fields.IntegerField(null=True, blank=True)
    duree_spectacle = models.fields.TimeField(null=True, blank=True)
    cachet_ttc = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    date_spectacle = models.fields.DateField(null=True, blank=True)

    info_complementaire = models.fields.TextField(blank=True)


    def __str__(self):
        return f'{self.numero}'


class Facturation(models.Model):
    qte = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    prix = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    total = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    apply_tax = models.fields.BooleanField(default=True, blank=True)
    tax = models.fields.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.total}'

test_liste/liste/forms.py
from django import forms
from liste.models import Prestation, Devis, Facturation

import calculation


class TestForm(forms.ModelForm):
    total = forms.DecimalField(
        widget=calculation.FormulaInput('qte*prix') # <- using single math expression
    )
    #apply_tax = forms.BooleanField(initial=True)
    tax = forms.DecimalField(
        # using math expression and javascript functions.
        widget=calculation.FormulaInput('apply_tax ? parseFloat(total/11).toFixed(2) : 0.0')
    )

    class Meta:
        model = Facturation
        fields = '__all__'


class PrestationForm(forms.ModelForm):
    class Meta:
        model = Prestation
        fields = '__all__'

class DevisForm(forms.ModelForm):
    class Meta:
        model = Devis
        fields = '__all__'

test_liste/liste/views.py
from django.shortcuts import render
from liste.forms import PrestationForm, DevisForm, TestForm

from django.http import JsonResponse
from .models import Prestation

import io
from django.http import FileResponse
from reportlab.pdfgen import canvas


def get_artiste(request, artiste_id):
    titre_spectacle = Prestation.objects.get(id=artiste_id).titre_spectacle
    nb_artiste = Prestation.objects.get(id=artiste_id).nb_artiste
    nb_technicien = Prestation.objects.get(id=artiste_id).nb_technicien
    duree_spectacle = Prestation.objects.get(id=artiste_id).duree_spectacle.strftime('%H:%M')
    cachet_ttc = Prestation.objects.get(id=artiste_id).cachet_ttc

    return JsonResponse({'titre_spectacle': titre_spectacle,
                         'nb_artiste': nb_artiste,
                         'nb_technicien': nb_technicien,
                         'duree_spectacle': duree_spectacle,
                         'cachet_ttc': cachet_ttc,
                         })


def some_view(request):
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename="hello.pdf")


def test(request):
    return render(request, 'liste/test.html')


def calcul(request):
    if request.method == 'POST':
        form = TestForm(request.POST)
        if form.is_valid():
            facturation = form.save()
            return render(request, 'liste/test.html')
    else:
        form = TestForm()

    return render(request, 'liste/calcul.html', {'form': form})


def prestation_create(request):
    if request.method == 'POST':
        form = PrestationForm(request.POST)
        if form.is_valid():
            prestation = form.save()
            return render(request, 'liste/test.html')
    else:
        form = PrestationForm()

    return render(request, 'liste/prestation_create.html', {'form': form})

def devis_create(request):
    if request.method == 'POST':
        form = DevisForm(request.POST)
        if form.is_valid():
            devis = form.save()
            return render(request, 'liste/test.html')
    else:
        form = DevisForm()

    return render(request, 'liste/devis_create.html', {'form': form})

test_liste/liste/templates/liste/base.html
{% load static %}

<html>
    <link rel="stylesheet" href="{% static 'booking/styles.css' %}" />

    <head>
        <title>Test liste</title>
        <h3>TEST</h3>
    </head>

    <body>

        {% block content %}{% endblock %}

    </body>
</html>

test_liste/liste/templates/liste/calcul.html
{% extends 'liste/base.html' %}

{% block content %}

<h3>Calcul</h3>

<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Créer</button>
</form>

{{ form.media }}

{% endblock %}

test_liste/liste/templates/liste/devis_create.html
{% extends 'liste/base.html' %}

{% block content %}

<h3>Création d'un nouveau devis</h3>

<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Créer</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function() {

        document.querySelector("#id_artiste").addEventListener("change", function() {
            var artisteId = this.value;
            fetch(`/get-artiste/${artisteId}/`)
                .then(response => response.json())
                .then(data => {
                    document.querySelector("#id_titre_spectacle").value = data.titre_spectacle;
                    document.querySelector("#id_nb_artiste").value = data.nb_artiste;
                    document.querySelector("#id_nb_technicien").value = data.nb_technicien;
                    document.querySelector("#id_duree_spectacle").value = data.duree_spectacle;
                    document.querySelector("#id_cachet_ttc").value = data.cachet_ttc;
                });
        });
    });

</script>

{% endblock %}

test_liste/liste/templates/liste/prestation_create.html
{% extends 'liste/base.html' %}

{% block content %}

<h3>Création d'une nouvelle prestation</h3>

<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Créer</button>
</form>

{% endblock %}

test_liste/liste/templates/liste/test.html
{% extends 'liste/base.html' %}

{% block content %}

<form>
    <button type="submit" formaction="{% url 'prestation-create' %}">Créer prestation</button>
    <button type="submit" formaction="{% url 'devis-create' %}">Créer devis</button>
    <button type="submit" formaction="{% url 'some-view' %}">Etat pdf</button>
    <button type="submit" formaction="{% url 'calcul' %}">Calcul</button>
</form>


{% endblock %}